@startuml
!include .\\SWE-Routenplaner-Business\Program.puml
!include .\\SWE-Routenplaner-Business\Tour.puml
!include .\\SWE-Routenplaner-Business\TourLog.puml
!include .\\SWE-Routenplaner-Business\Tours.puml
!include .\\SWE-Routenplaner-DataAccess\IQuery.puml
!include .\\SWE-Routenplaner-DataAccess\Program.puml
!include .\\SWE-Routenplaner-DataAccess\RESTRequest.puml
!include .\\SWEN2-TourPlanner-Model\Program.puml
!include .\\SWEN2-TourPlanner-Model\RESTRequest.puml
!include .\\SWEN2-Tourplanner-ViewModel\ToursViewModel.puml
!include .\\SWEN2-REST\SWEN2-REST\Program.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\App.xaml.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\AssemblyInfo.puml
!include .\\SWEN2-REST\SWEN2-REST\BL\MapQuestContext.puml
!include .\\SWEN2-REST\SWEN2-REST\DAL\FileHandler.puml
!include .\\SWEN2-REST\SWEN2-REST\DAL\TourContext.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Commands\Command.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Commands\ParaCommand.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Models\TourListModel.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Models\TourLogModel.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Models\TourModel.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\ViewModels\CreateTourLogViewModel.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\ViewModels\CreateTourViewModel.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\ViewModels\ModifyTourLogsViewModel.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\ViewModels\ModifyTourViewModel .puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\ViewModels\ToursViewModel.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Views\CreateTourLogWindow.xaml.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Views\CreateTourWindow.xaml.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Views\DeleteDialogue.xaml.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Views\ModifyTourLogWindow.xaml.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Views\ModifyTourWindow.xaml.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Views\SearchBar.xaml.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\Views\ToursWindow.xaml.puml
!include .\\SWE-Routenplaner-Business\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\SWE-Routenplaner-Business\obj\Debug\net6.0\SWE-Routenplaner-Business.AssemblyInfo.puml
!include .\\SWE-Routenplaner-Business\obj\Debug\net6.0\SWE-Routenplaner-Business.GlobalUsings.g.puml
!include .\\SWE-Routenplaner-DataAccess\obj\Debug\net6.0-windows\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\SWE-Routenplaner-DataAccess\obj\Debug\net6.0-windows\SWE-Routenplaner-DataAccess.AssemblyInfo.puml
!include .\\SWE-Routenplaner-DataAccess\obj\Debug\net6.0-windows\SWE-Routenplaner-DataAccess.GlobalUsings.g.puml
!include .\\SWEN2-REST\SWEN2-REST\BL\Controllers\TourController.puml
!include .\\SWEN2-REST\SWEN2-REST\BL\Controllers\TourLogController.puml
!include .\\SWEN2-REST\SWEN2-REST\BL\Models\Tour.puml
!include .\\SWEN2-REST\SWEN2-REST\BL\Models\TourLog.puml
!include .\\SWEN2-REST\SWEN2-REST\BL\Models\Tours.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\App.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\GeneratedInternalTypeHelper.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\GeneratedInternalTypeHelper.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_1ml1kr3l_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_2iil30mz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_3eop4q2v_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_3memefv4_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_Content.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_Content.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_dr3wdiqg_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_efvcpoq2_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_hkd0rsym_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_ir2ove04_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_01giv45u_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_01h0gpib_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_0bxgi5u3_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_0ek3jgem_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_0gmgnmsy_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_0jgi5lic_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_0onj0elo_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_0pmeszn4_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_13ceds5d_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_1cgqtfhq_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_1dbmgept_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_1hiyc0gw_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_1njdv40a_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_1q4rzhbr_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_1r55ozp5_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_1yhgaii4_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_2jtdrn2c_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_2qtcy05u_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_2sf041z1_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_2zg10rfp_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_323nuk53_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_3dlcuyam_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_3fvuwmku_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_3lfvxmon_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_3qg21e3t_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_3ujdne3t_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_3uyz1nkl_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_3wbazop1_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_4nobr4j5_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_4ocvkr5p_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_4w0ulqvl_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_4ycell0a_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_4zzjv4ov_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_55oskms5_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_5awiwl5a_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_5niditvz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_5p3jlbhc_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_a53ry5wt_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_abqygz41_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_acffdso5_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_advyqahc_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_aep3bifj_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_asghfies_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ayebqk4e_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_b0l4rghz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_b2ba4xh4_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_b4nnpz0a_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_bcsxggga_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_bwx3mo4r_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ca0yodoa_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_cdkusllr_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_cfua0mhm_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_Content.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_Content.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_d5fwz5du_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_d5r33iwt_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_dcwv1c0t_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ddxvrkgz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_dhoyuorr_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_diiznbuk_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_e2uzdx1e_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ebnxyqs4_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_efxyy0c2_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ezoszzzd_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_fgyvlcfy_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_fvn2ky0k_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_g1rveomo_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_gfj5xzhj_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_gl0bg2am_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_gn0i4nps_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_h1ki0ucs_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_h3fdaasg_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_h4w32qvt_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_hqj1r0qs_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_hsvsajxp_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_iev3ipdk_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_iplas0wh_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ivvflnwt_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ixfodk3b_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_jd0hludu_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_k5epyl2c_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_kcmb0g5j_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_knrxu51q_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ktwjoyqn_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_l3qizvyt_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_le3bjkxz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_lontag0h_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_lvampp5k_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_m5kqeylx_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_medq1pqc_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_mknjytwc_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_mof2ij1h_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_mqz15dp5_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_mtxxrkta_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_mv4ujr3g_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_mwpqr1k3_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_n3psc5gz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_n4nrudw0_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_nenxhqwa_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_nheec50m_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_nmkedr5g_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_nuffxilx_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_o0mif0my_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_o2iukn1l_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_o5nsprov_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_oambdee0_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ocf0wjdg_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_okrtcyn3_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_opzvktld_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_orswyj1w_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_orvfzp25_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ozievi2r_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_pbyo35vs_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_pfkvy0rr_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_pjsr2qn5_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_pjz5m5ok_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_pxacmf44_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_qaii4wwf_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_qf2e0dsk_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_qg5jvedz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_qgexjr0f_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_qnilxvmu_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_qxvam5f5_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_r5pybnxu_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_rq24pqbh_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_s2at4fdc_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_s2tuggai_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_sdofm0ai_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ssmhgd32_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_sxf10msa_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_syk4uei1_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_te2jqc2r_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_tglpugtw_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_tk0v1xvk_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_tkoezekc_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_tpqpfq54_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_u1vub0ka_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_u30auz1w_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_u5hbxhow_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ufbmwqqi_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ukrdy2wa_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_uoarkbu2_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_uvqsbiuf_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_uxdnnapn_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_v1et4p0f_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_v1fn3pxr_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_v4rq3b3g_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_vbpedeoc_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_vgqvrfl3_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_vjoajl1k_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_vjxrr2t4_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_vltcceg1_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_vrcuu4dg_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_w24gyzzg_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_w2hw0gss_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_wezggy5x_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_wfpbuvoi_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_wqmw4bvn_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_wubblt3c_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_wxc2tpo3_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_wyxaqbru_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_xstpu4pq_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_xtg0ueyf_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_y2rcs33l_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_yar4qrnx_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ycis5c1a_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ygqyajm3_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ygtsikbf_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ywlcmdky_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_ywlig15d_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_yypza1mx_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_yzugh4x3_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_z3p05c5y_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_z3twyp1k_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_z43kbnjt_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_zblayg2m_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_zfdfk13o_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_zxg1vsb5_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-REST\SWEN2-REST\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\SWEN2-REST\SWEN2-REST\obj\Debug\net6.0\SWEN2-REST.AssemblyInfo.puml
!include .\\SWEN2-REST\SWEN2-REST\obj\Debug\net6.0\SWEN2-REST.GlobalUsings.g.puml
!include .\\SWEN2-REST\SWEN2-REST\obj\Debug\net6.0\SWEN2-REST.MvcApplicationPartsAssemblyInfo.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\icons\UserControl1.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\UILayer\LogList.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\UILayer\MainWindow.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\UILayer\SearchBar.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\UILayer\TourDetails.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\UILayer\TourList.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\UILayer\TourListItem.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\UILayer\TourListView.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\CreateTour.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\CreateTourWindow.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\CreateTourWindow.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\LogList.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\LogList.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\MainWindow.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\MainWindow.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\SearchBar.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\SearchBar.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\TourDetails.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\TourDetails.g.i.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\TourList.g.puml
!include .\\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\TourList.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\App.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\App.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\GeneratedInternalTypeHelper.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\GeneratedInternalTypeHelper.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\MainWindow.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_14t3hmoa_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_Content.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_Content.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_jq2cnip2_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_uhehslwz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_v51sg1q1_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner-View_wb0ya35q_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_Content.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_Content.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_et1gu3ri_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_i3ednpq4_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_mhkkdnlz_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_pihzienm_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_qhqs4ael_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_srx55x5o_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\SWEN2-TourPlanner_vin2032m_wpftmp.AssemblyInfo.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Usercontrols\LogList.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Usercontrols\TourDetails.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Usercontrols\TourList.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\CreateTourWindow.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\CreateTourWindow.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\LogList.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\LogList.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\MainWindow.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\MainWindow.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\SearchBar.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\SearchBar.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\TourDetails.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\TourDetails.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\TourList.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\View\TourList.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\CreateTourLogWindow.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\CreateTourWindow.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\CreateTourWindow.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\DeleteDialogue.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\ModifyTourLogWindow.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\ModifyTourWindow.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\SearchBar.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\SearchBar.g.i.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\ToursWindow.g.puml
!include .\\SWEN2-UI\SWEN2-TourPlanner\obj\Debug\net6.0-windows\Views\ToursWindow.g.i.puml
@enduml
